# Generated by Django 4.0 on 2022-01-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('vibor_kategor', models.CharField(choices=[('1', 'Закуска'), ('2', 'Основное'), ('3', 'Десерт'), ('4', 'Напиток'), ('5', 'Суп')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvan', models.CharField(max_length=30, verbose_name='Название ресторана')),
                ('adres', models.CharField(max_length=50, verbose_name='Адрес')),
                ('telefon', models.IntegerField(verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Bluda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('foto', models.FileField(upload_to='img/', verbose_name='Фото блюда')),
                ('full_text', models.TextField(verbose_name='Полный состав')),
                ('masa', models.IntegerField(verbose_name='Вес')),
                ('cena', models.FloatField(verbose_name='Цена в рублях')),
                ('kategor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoran.kategor')),
                ('name_restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoran.restoran')),
            ],
        ),
    ]
