# Generated by Django 4.0 on 2022-01-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0002_alter_bluda_options_alter_kategor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoran',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание рестрана'),
        ),
    ]
