# Generated by Django 4.0 on 2022-01-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0004_restoran_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluda',
            name='kategor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restoran.kategor'),
        ),
    ]
